# ===============================================
# CONFIGURACAO GERAL DA APLICACAO
# ===============================================
spring.application.name=projetomercado
# CRIE NA RAIZ DO TEU PROJETO um arquivo chamado .env
# Tudo que estiver entre ${} e o nome da variavel que devera ter no .env
# Importa as variaveis do arquivo .env
spring.config.import=optional:file:.env[.properties]

# ===============================================
# BANCO DE DADOS (H2 IN-MEMORY)
# ===============================================
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

# ===============================================
# SWAGGER / OPENAPI
# ===============================================
springdoc.swagger-ui.path=/swagger-ui.html

# ===============================================
# DEVTOOLS
# ===============================================
## NAO MODIFICAR ISSO
spring.devtools.livereload.enabled=false
spring.devtools.restart.trigger-file=.reloadTriggerIfRestartIsFalse

# ===============================================
# LOGGING (PARA DEBUG)
# ===============================================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#logging.level.org.hibernate.type=trace

# ===============================================
# CONFIGURACOES DE E-MAIL (MAILTRAP)
# ===============================================
spring.mail.host=live.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=${MT_USERNAME}
spring.mail.password=${MT_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
email.sender.from=nao-responda@projeto-mercado.dedyn.io

# "Interruptor" para ligar/desligar o envio de e-mail de confirmacao
email.confirmation.enabled=false

# "Interruptor" para ligar/desligar o envio de e-mail de recuperacao de senha
email.reset.enabled=false

# ===============================================
# CONFIGURACAO DO OAUTH2 GOOGLE
# ===============================================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_OAUTH2_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_OAUTH2_SECRET}
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/oauth2/callback/{registrationId}
spring.security.oauth2.client.registration.google.scope=email, profile
app.auth.oauth2.authorizedRedirectUris=http://localhost:5173/oauth2/redirect

# ===============================================
# CONFIGURACAO DO SERVIDOR WEB
# ===============================================
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

# ===============================================
# CONFIGURACAO DO JWT (JSON Web Token)
# ===============================================
# Segredo para assinar os tokens (DEVE SER LONGO E SEGURO)
jwt.secret=56c76e49f861404d8d97760b3b4a89d9

# Emissor do token
jwt.issuer=prati-projeto-mercado

# Duracao do Access Token (em horas)
jwt.expiration.access-token.hours=1

# Duracao do Refresh Token (em horas)
jwt.expiration.refresh-token.hours=12

# ===============================================
# CONFIGURACAO DO TOKEN DE RECUPERACAO DE SENHA
# ===============================================
# Duracao do Token de Recuperacao de Senha (em minutos)
password.reset.token.expiry.minutes=15
