spring.application.name=projetomercado


spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true


springdoc.swagger-ui.path=/swagger-ui.html


spring.devtools.restart.enabled=false


logging.level.org.hibernate.SQL=DEBUG


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=agathakmachado5@gmail.com
spring.mail.password=uopp hxtn htio ynub
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
email.sender.from=nao-responda@projetomercado.com

# "Interruptor" para ligar/desligar o envio de e-mail de confirmacao
email.confirmation.enabled=true

spring.security.oauth2.client.registration.google.client-id=542124276337-321lush0fmhlt0bbkp0us22r258b1fnj.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/callback/{registrationId}
spring.security.oauth2.client.registration.google.scope=email, profile
app.auth.oauth2.authorizedRedirectUris=http://localhost:5173/oauth2/redirect


server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true 
