spring.application.name=projetomercado

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html

spring.devtools.restart.enabled=false
spring.devtools.restart.trigger-file=.reloadTriggerIfRestartIsFalse

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.type=trace

spring.security.oauth2.client.registration.google.client-id=542124276337-321lush0fmhlt0bbkp0us22r258b1fnj.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri= {baseUrl}/oauth2/callback/{registrationId}
spring.security.oauth2.client.registration.google.scope=email, profile

#configuraÃ§Ãµes de email (gmal)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=SEU_PROPRIO_EMAIL@gmail.com
spring.mail.password=A_SENHA_DE_16_CARACTERES_GERADA_AQUI
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


app.auth.oauth2.authorizedRedirectURis=http://localhost:5173/oauth2/redirect

